# 1 - Utilize a versão "3" no arquivo;
version: '3'
# 2 - Crie um service para subir a plataforma. Para isso, utilize a imagem ghost:1-alpine;
services:
  ghost:
    image: ghost:1-alpine
# 3 - Publique a porta 2368, fazendo bind também para a 2368;
    ports: 
     - 2368:2368
